spring.datasource.url=jdbc:postgresql://localhost:5432/evento-fasipe
# Tenta ler a variavel DB_USER, se nao achar, usa 'postgres' como padrao
spring.datasource.username=${DB_USER:postgres}
# Tenta ler a variavel DB_PASSWORD, se nao achar, fica vazio (ou da erro)
spring.datasource.password=${DB_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true